import path from 'path';
import { defineConfig, loadEnv, UserConfig } from 'vite';
import react from '@vitejs/plugin-react';
import copy from 'rollup-plugin-copy';
import stylelintPlugin from 'vite-plugin-stylelint';
import imageMinPlugin from 'vite-plugin-imagemin';
import AutoImport from 'unplugin-auto-import/vite';
import { VitePWA } from 'vite-plugin-pwa';
import { setupMockApi } from './src/mocks/vite-mock-api';
import type { Plugin } from 'vite';

function mockApiPlugin(useMockApi: boolean): Plugin {
  return {
    name: 'vite-mock-api',
    configureServer(server) {
      if (useMockApi) {
        setupMockApi(server.middlewares);
      }
    },
  };
}

export default defineConfig(({ mode }): UserConfig => {
  const env = loadEnv(mode, process.cwd(), '');
  const port = env.PORT || 8001;
  const useMockApi = env.USE_MOCK_API !== 'false';

  return {
    base: '/',
    build: {
      target: 'es2015',
      outDir: 'public',
      emptyOutDir: true,
      manifest: true,
      chunkSizeWarningLimit: 1000,
      rollupOptions: {
        output: {
          entryFileNames: 'app.[hash].js',
          chunkFileNames: 'app.[hash].chunk.js',
          assetFileNames: 'assets.[hash].[ext]',
        },
      },
    },
    mode: env.NODE_ENV,
    server: {
      host: '0.0.0.0',
      port: port as number,
    },
    define: {
      API_URL: JSON.stringify(env.API_URL),
      SOCKET_URL: JSON.stringify(env.SOCKET_URL),
      APP_URL: JSON.stringify(env.APP_URL),
      YOUTUBE_API_KEY: JSON.stringify(env.YOUTUBE_API_KEY),
      NODE_ENV: JSON.stringify(env.NODE_ENV),
      PORT: JSON.stringify(env.PORT),
      SUPERSET_URL: JSON.stringify(env.SUPERSET_URL),
    },
    resolve: {
      alias: {
        components: path.resolve(__dirname, 'src/components'),
        containers: path.resolve(__dirname, 'src/containers'),
        config: path.resolve(__dirname, 'src/config'),
        api: path.resolve(__dirname, 'src/api'),
        types: path.resolve(__dirname, 'src/types'),
        styles: path.resolve(__dirname, 'src/styles'),
        pages: path.resolve(__dirname, 'src/pages'),
        i18n: path.resolve(__dirname, 'i18n'),
        utils: path.resolve(__dirname, 'src/utils'),
        assets: path.resolve(__dirname, 'assets'),
        src: path.resolve(__dirname, 'src'),
        enums: path.resolve(__dirname, 'src/enums'),
        stores: path.resolve(__dirname, 'src/stores'),
        hooks: path.resolve(__dirname, 'src/hooks'),
        mocks: path.resolve(__dirname, 'src/mocks'),
      },
      extensions: ['.tsx', '.ts', '.jsx', '.js', '.json'],
    },
    plugins: [
      mockApiPlugin(useMockApi),
      react({
        babel: {
          plugins: [
            [
              'babel-plugin-styled-components',
              {
                displayName: true,
                fileName: false,
              },
            ],
          ],
        },
      }),
      stylelintPlugin(),
      imageMinPlugin({
        gifsicle: {
          optimizationLevel: 7,
          interlaced: true,
        },
        optipng: {
          optimizationLevel: 7,
        },
        mozjpeg: {
          quality: 80,
        },
        pngquant: {
          quality: [0.8, 0.9],
          speed: 4,
        },
        svgo: {
          plugins: [
            {
              name: 'removeViewBox',
            },
            {
              name: 'removeEmptyAttrs',
              active: false,
            },
          ],
        },
      }),
      copy({
        verbose: true,
        hook: 'writeBundle',
        targets: [
          {
            src: 'assets/fonts',
            dest: 'public/assets',
          },
          {
            src: 'assets/images',
            dest: 'public/assets',
          },
          {
            src: 'assets/icons',
            dest: 'public/assets',
          },
        ],
      }),
      AutoImport({
        eslintrc: {
          enabled: true,
        },
        imports: [
          'react',
          {
            '@mui/material': [
              ['Table', 'MUITable'],
              ['TableRow', 'MUITableRow'],
              ['TableCell', 'MUITableCell'],
              ['TableHead', 'MUITableHead'],
              ['TableBody', 'MUITableBody'],
              ['TableContainer', 'MUITableContainer'],
              ['Pagination', 'MUIPagination'],
              ['Skeleton', 'MUISkeleton'],
              ['InputAdornment', 'MUIInputAdornment'],
              ['Button', 'MUIButton'],
              ['TextField', 'MUITextField'],
              ['Box', 'MUIBox'],
              ['Dialog', 'MUIDialog'],
              ['Drawer', 'MUIDrawer'],
              ['Popper', 'MUIPopper'],
              ['DialogActions', 'MUIDialogActions'],
              ['DialogTitle', 'MUIDialogTitle'],
              ['DialogContent', 'MUIDialogContent'],
              ['Fade', 'MUIFade'],
              ['Grid', 'MUIGrid'],
              ['Tab', 'MUITab'],
              ['Tabs', 'MUITabs'],
              ['IconButton', 'MUIIconButton'],
              ['Tooltip', 'MUITooltip'],
              ['Slider', 'MUISlider'],
              ['Menu', 'MUIMenu'],
              ['Fade', 'MUIFade'],
              ['MenuItem', 'MUIMenuItem'],
              ['LinearProgress', 'MUILinearProgress'],
              ['CircularProgress', 'MUICircularProgress'],
              ['Switch', 'MUISwitch'],
              ['Breadcrumbs', 'MUIBreadcrumbs'],
              ['AppBar', 'MUIAppBar'],
              ['Toolbar', 'MUIToolbar'],
              ['Badge', 'MUIBadge'],
              ['BottomNavigation', 'MUIBottomNavigation'],
              ['BottomNavigationAction', 'MUIBottomNavigationAction'],
              ['Link', 'MUILink'],
              ['Select', 'MUISelect'],
              ['InputLabel', 'MUIInputLabel'],
              ['FormControl', 'MUIFormControl'],
              'useTheme',
              'useMediaQuery',
            ],
          },
          {
            '@mui/lab': [['LoadingButton', 'MUILoadingButton']],
          },
          {
            'lodash-es': [
              'cloneDeep',
              'range',
              'replace',
              'assign',
              'keyBy',
              'pick',
              'reduce',
              'get',
              'some',
              'forEach',
              'isEmpty',
              'flatten',
              'camelCase',
              'snakeCase',
              'isArray',
              'isObject',
              'keys',
              'size',
              'uniqBy',
              'head',
              'has',
              'omit',
              'isEqual',
              'padStart',
              'sortBy',
              'toLower',
              'trim',
              'isDate',
              'isNull',
              'kebabCase',
              'map',
              'find',
              'findIndex',
              'filter',
              'isString',
              'entries',
              'values',
              'debounce',
              'uniq',
              'orderBy',
              'truncate',
              'random',
              'round',
              'isNumber',
            ],
          },
          {
            '@mui/material/styles': [
              'alpha',
              'styled',
              'keyframes',
              'css',
              'createTheme',
              'ThemeProvider',
            ],
          },
          {
            'react-i18next': [
              'useTranslation',
              'Translation',
              'initReactI18next',
              'Trans',
            ],
          },
          {
            'react-helmet-async': ['Helmet', 'HelmetProvider'],
          },
          {
            'react-router-dom': [
              'createBrowserRouter',
              'RouterProvider',
              'Link',
              'NavLink',
              'Outlet',
              'useNavigate',
              'useMatch',
              'useMatches',
              'useParams',
              'useLocation',
              'useSearchParams',
            ],
          },
          {
            'react-hook-form': ['Controller', 'useForm', 'useController'],
          },
          {
            'react-query': [
              'useMutation',
              'useQuery',
              'useQueryClient',
              'useQueries',
              'QueryClient',
              'QueryClientProvider',
            ],
          },
          {
            ahooks: [
              'useToggle',
              'useBoolean',
              'useDebounce',
              'usePrevious',
              'useLongPress',
              'useResetState',
              'useUpdateEffect',
              'useSize',
              'useClickAway',
              'useMount',
              'useUnmount',
              'useMemoizedFn',
              'useDocumentVisibility',
              'useHover',
            ],
          },
          {
            '@phosphor-icons/react': [
              ['At', 'AtIcon'],
              ['Heart', 'HeartIcon'],
              ['FileDoc', 'FileDocIcon'],
              ['CodesandboxLogo', 'CodesandboxLogoIcon'],
              ['ShareNetwork', 'ShareNetworkIcon'],
              ['ChatCircleText', 'ChatCircleTextIcon'],
              ['DotsThree', 'DotsThreeIcon'],
              ['DotsThreeVertical', 'DotsThreeVerticalIcon'],
              ['FileZip', 'FileZipIcon'],
              ['PauseCircle', 'PauseCircleIcon'],
              ['PlayCircle', 'PlayCircleIcon'],
              ['XCircle', 'XCircleIcon'],
              ['Eye', 'EyeIcon'],
              ['EyeSlash', 'EyeSlashIcon'],
              ['Prohibit', 'ProhibitIcon'],
              ['WarningOctagon', 'WarningOctagonIcon'],
              ['AndroidLogo', 'AndroidLogoIcon'],
              ['AppleLogo', 'AppleLogoIcon'],
              ['ArrowCircleLeft', 'ArrowCircleLeftIcon'],
              ['ArrowCircleRight', 'ArrowCircleRightIcon'],
              ['ArrowLeft', 'ArrowLeftIcon'],
              ['Circle', 'CircleIcon'],
              ['CheckCircle', 'CheckCircleIcon'],
              ['House', 'HouseIcon'],
              ['Envelope', 'EnvelopeIcon'],
              ['PhoneCall', 'PhoneCallIcon'],
              ['UserCircle', 'UserCircleIcon'],
              ['Warning', 'WarningIcon'],
              ['WarningCircle', 'WarningCircleIcon'],
              ['Info', 'InfoIcon'],
              ['X', 'XIcon'],
              ['Vibrate', 'VibrateIcon'],
              ['ListBullets', 'ListBulletsIcon'],
              ['Plus', 'PlusIcon'],
              ['Play', 'PlayIcon'],
              ['Check', 'CheckIcon'],
              ['Bell', 'BellIcon'],
              ['ListDashes', 'ListDashesIcon'],
              ['Question', 'QuestionIcon'],
              ['MagnifyingGlass', 'MagnifyingGlassIcon'],
              ['Upload', 'UploadIcon'],
              ['UploadSimple', 'UploadSimpleIcon'],
              ['MapPin', 'MapPinIcon'],
              ['Note', 'NoteIcon'],
              ['Image', 'ImageIcon'],
              ['Crop', 'CropIcon'],
              ['ArrowsClockwise', 'ArrowsClockwiseIcon'],
              ['ArrowClockwise', 'ArrowClockwiseIcon'],
              ['X', 'XIcon'],
              ['DownloadSimple', 'DownloadSimpleIcon'],
              ['PlusCircle', 'PlusCircleIcon'],
              ['User', 'UserIcon'],
              ['MagnifyingGlassMinus', 'MagnifyingGlassMinusIcon'],
              ['MagnifyingGlassPlus', 'MagnifyingGlassPlusIcon'],
              ['RadioButton', 'RadioButtonIcon'],
              ['VideoCamera', 'VideoCameraIcon'],
              ['MusicNotesPlus', 'MusicNotesPlusIcon'],
              ['Link', 'LinkIcon'],
              ['FileText', 'FileTextIcon'],
              ['ImageSquare', 'ImageSquareIcon'],
              ['UserCirclePlus', 'UserCirclePlusIcon'],
              ['ChatCenteredText', 'ChatCenteredTextIcon'],
              ['NavigationArrow', 'NavigationArrowIcon'],
              ['SelectionPlus', 'SelectionPlusIcon'],
              ['TrashSimple', 'TrashSimpleIcon'],
              ['PencilLine', 'PencilLineIcon'],
              ['NotePencil', 'NotePencilIcon'],
              ['PaperPlaneTilt', 'PaperPlaneTiltIcon'],
              ['ArrowsOutCardinal', 'ArrowsOutCardinalIcon'],
              ['LinkSimpleHorizontal', 'LinkSimpleHorizontalIcon'],
              ['CaretDown', 'CaretDownIcon'],
              ['CaretUp', 'CaretUpIcon'],
              ['ArrowRight', 'ArrowRightIcon'],
              ['ArrowUp', 'ArrowUpIcon'],
              ['ArrowDown', 'ArrowDownIcon'],
              ['Swap', 'SwapIcon'],
              ['CodesandboxLogo', 'CodesandboxLogoIcon'],
              ['CaretLeft', 'CaretLeftIcon'],
              ['CaretRight', 'CaretRightIcon'],
              ['PencilSimple', 'PencilSimpleIcon'],
              ['Flag', 'FlagIcon'],
              ['CopySimple', 'CopySimpleIcon'],
              ['Buildings', 'BuildingsIcon'],
              ['SignOut', 'SignOutIcon'],
              ['Gear', 'GearIcon'],
              ['ChartLine', 'ChartLineIcon'],
            ],
          },
          {
            zustand: ['create', 'useStore'],
          },
          {
            from: 'zustand',
            imports: ['StoreApi', 'UseBoundStore', 'StateCreator'],
            type: true,
          },
          {
            from: 'react',
            imports: [
              'Dispatch',
              'SetStateAction',
              'FunctionComponent',
              'ReactNode',
              'ReactElement',
              'Key',
              ['MouseEvent', 'ReactMouseEvent'],
              ['KeyboardEvent', 'ReactKeyboardEvent'],
              'ComponentType',
              'ComponentProps',
              'ChangeEvent',
              'Ref',
              'SyntheticEvent',
              'RefObject',
              'CSSProperties',
              'ElementRef',
              'ForwardRefRenderFunction',
              'MutableRefObject',
              'UIEventHandler',
            ],
            type: true,
          },
          {
            from: 'react-query',
            imports: [
              'QueryKey',
              'UseQueryOptions',
              'UseQueryResult',
              'QueriesResults',
              'QueriesOptions',
            ],
            type: true,
          },
          {
            from: '@mui/material',
            imports: [
              'Components',
              'Theme',
              'BoxProps',
              'TextFieldProps',
              'DialogProps',
              'PopperProps',
              'IconButtonProps',
              'SwitchProps',
              'TooltipProps',
              'TabsProps',
              'ModalProps',
              'SxProps',
              'SelectProps',
              'SelectChangeEvent',
            ],
            type: true,
          },
          {
            from: '@mui/lab',
            imports: ['LoadingButtonProps'],
            type: true,
          },
          {
            from: 'react-hook-form',
            imports: [
              'RegisterOptions',
              'Control',
              'FieldValues',
              'FieldErrors',
              'UseFormReturn',
            ],
            type: true,
          },
        ],
        dirs: ['src/shared'],
        dts: 'src/types/auto-imports.d.ts',
      }),
      VitePWA({
        registerType: 'autoUpdate',
        includeAssets: [
          'assets/icons/favicon.ico',
          'assets/icons/apple-icon.png',
        ],
        manifest: {
          name: 'React Boilerplate',
          short_name: 'React Boilerplate',
          icons: [
            {
              src: 'assets/icons/android-icon-192x192.png',
              sizes: '192x192',
              type: 'image/png',
            },
          ],
        },
      }),
    ],
  };
});
