/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const StrictMode: typeof import('react').StrictMode
  const Suspense: typeof import('react').Suspense
  const ThemeProvider: typeof import('styled-components').ThemeProvider
  const cloneElement: typeof import('react').cloneElement
  const createContext: typeof import('react').createContext
  const createGlobalStyle: typeof import('styled-components').createGlobalStyle
  const createRef: typeof import('react').createRef
  const css: typeof import('styled-components').css
  const forwardRef: typeof import('react').forwardRef
  const isValidElement: typeof import('react').isValidElement
  const keyframes: typeof import('styled-components').keyframes
  const lazy: typeof import('react').lazy
  const memo: typeof import('react').memo
  const startTransition: typeof import('react').startTransition
  const styled: typeof import('styled-components').default
  const useCallback: typeof import('react').useCallback
  const useContext: typeof import('react').useContext
  const useDebugValue: typeof import('react').useDebugValue
  const useDeferredValue: typeof import('react').useDeferredValue
  const useEffect: typeof import('react').useEffect
  const useId: typeof import('react').useId
  const useImperativeHandle: typeof import('react').useImperativeHandle
  const useInsertionEffect: typeof import('react').useInsertionEffect
  const useLayoutEffect: typeof import('react').useLayoutEffect
  const useMemo: typeof import('react').useMemo
  const useReducer: typeof import('react').useReducer
  const useRef: typeof import('react').useRef
  const useState: typeof import('react').useState
  const useSyncExternalStore: typeof import('react').useSyncExternalStore
  const useTransition: typeof import('react').useTransition
}
// for type re-export
declare global {
  // @ts-ignore
  export type { FunctionComponent, ReactNode, ReactElement, Key, MouseEvent as ReactMouseEvent, KeyboardEvent as ReactKeyboardEvent, ClipboardEvent as ReactClipboardEvent, ComponentType, ComponentProps, ChangeEvent, Ref, RefObject, Dispatch, SetStateAction, CSSProperties } from 'react'
  import('react')
  // @ts-ignore
  export type { DefaultTheme } from 'styled-components'
  import('styled-components')
}
